<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327094013 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT NOT NULL, issues JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, listing_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E7F15B5FD4619D1A ON audit_report (listing_id)');
        $this->addSql('ALTER TABLE audit_report ADD CONSTRAINT FK_E7F15B5FD4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_report DROP CONSTRAINT FK_E7F15B5FD4619D1A');
        $this->addSql('DROP TABLE audit_report');
    }
}
